### ISSUE TITLE
Suddivisione grafica e notifica mancante 

### ISSUE THREAD

**Issue by bananabduh** [peppelg/argo_scuolanext_famiglia_unofficial_app#10]
Nella sezione "cosa è successo oggi " dell'app ufficiale si può distinguere gli argomenti dai voti grazie ad una suddivisione grafica ed una notifica . Nella versione unofficial non sono presenti , il che le rende difficile da notare . 
![IMG_20200204_174538](https://user-images.githubusercontent.com/57667351/73766331-2a52bd80-4776-11ea-9d0b-cbeab3763ce3.jpg)
![IMG_20200204_174154](https://user-images.githubusercontent.com/57667351/73766357-30489e80-4776-11ea-8a7a-d63859d8d8c4.jpg)

**Comment by peppelg** [comment]
Con l'ultima versione è +- simile
