### ISSUE TITLE
Errore filtro voti

### ISSUE THREAD

**Issue by bananabduh** [peppelg/argo_scuolanext_famiglia_unofficial_app#11]
Se metto il filtro per i voti mi arrivano tutte le notifiche di ogni singolo voto di nuovo
![IMG_20200217_225250](https://user-images.githubusercontent.com/57667351/74690797-54759800-51d8-11ea-878d-c597c52a2bbb.jpg)
![IMG_20200217_225249](https://user-images.githubusercontent.com/57667351/74690802-593a4c00-51d8-11ea-895c-6d93b574f35d.jpg)
![IMG_20200217_225248](https://user-images.githubusercontent.com/57667351/74690806-5d666980-51d8-11ea-88bd-5c5b11498208.jpg)
![IMG_20200217_225246](https://user-images.githubusercontent.com/57667351/74690811-60615a00-51d8-11ea-95fc-404b0114a145.jpg)
![IMG_20200217_225245](https://user-images.githubusercontent.com/57667351/74690815-65260e00-51d8-11ea-82ab-de30c5ab7c56.jpg)
![IMG_20200217_225243](https://user-images.githubusercontent.com/57667351/74690826-69522b80-51d8-11ea-9349-da0d4ae7348a.jpg)

 di ogni singolo voto

**Comment by peppelg** [comment]
non riesco a riprodurre il .problema, se ci riesci riapri issue e scrivi come si fa grz
