### ISSUE TITLE
Problemi bacheca

### ISSUE THREAD

**Issue by bananabduh** [peppelg/argo_scuolanext_famiglia_unofficial_app#13]
La bacheca permette di aprire i link ma non di scaricare file e mettere conferma di presa visione
![IMG_20200314_201538_653](https://user-images.githubusercontent.com/57667351/76688815-b6d38400-6630-11ea-9cf4-6dc3c4ea2b1e.jpg)
![IMG_20200314_201540_750](https://user-images.githubusercontent.com/57667351/76688818-ba670b00-6630-11ea-9355-dac70b1026a8.jpg)

**Comment by peppelg** [comment]
Yes lo so, devo vedere che richiesta fa per prendere il link di un allegato

**Comment by bananabduh** [comment]
Ah e non va nemmeno la conferma di adesione

**Comment by peppelg** [comment]
Tutto aggiuntos
