### ISSUE TITLE
Piccole mancanze dell'app :(

### ISSUE THREAD

**Issue by inagap** [peppelg/argo_scuolanext_famiglia_unofficial_app#20]
Premessa: sono osservazioni mie e da quel che vedo sembra essere un progetto molto amatoriale quindi veda lei che fare.
-una bella e simpatica media totale non farebbe male
-una sezione per controllare i dati anagrafici
-un altra sezione per poter prendere appuntamenti con i vari professori
-una sezione impostazioni più clean e comprensibile
-un simpatico tasto per il log out (ogni volta mi tocca resettare i dati dell'app :()
E credo di aver finito.
Hai fatto un lavoro eccellente e credo che in molti lo apprezzino, vista la scarsa qualità dell'app proprietaria; un piccolo ritocco in qua e là e questa app sarebbe top :).
P.S.: magari alcune cose non sono possibili da realizzare viste le limitazioni delle API quindi pace ✌🏻.

**Comment by inagap** [comment]
Posso aiutare nello sviluppo se dovessi riscontrare qualche problema o nel dubbio apro una modifica :)

**Comment by peppelg** [comment]
Gran parte di queste funzioni sono state aggiunte nell'ultimo aggiornamento.
Se vuoi aiutare le pull request sono sempre ben accette
