### ISSUE TITLE
Https response

### ISSUE THREAD

**Issue by bananabduh** [peppelg/argo_scuolanext_famiglia_unofficial_app#3]
Non mi manda le notifiche push e se accedo all'app mi segnala http response error seguito da un codice di errore. Questo succede solo se ho nuovi voti non ancora visualizzati.

**Comment by peppelg** [comment]
Penz che https error era un errore dei server di argo, cmq ora le notifiche funzionano .

**Comment by bananabduh** [comment]
Grazie
