### ISSUE TITLE
Notifiche

### ISSUE THREAD

**Issue by bananabduh** [peppelg/argo_scuolanext_famiglia_unofficial_app#4]
C'è un problema con le notifiche : appaiono ma senza icona 
![IMG_20200124_091126](https://user-images.githubusercontent.com/57667351/73054076-c41e8e80-3e89-11ea-987e-472d2f1f024c.jpg)
![IMG_20200124_091124](https://user-images.githubusercontent.com/57667351/73054462-cc2afe00-3e8a-11ea-9d38-5ade9c20870f.jpg)
![IMG_20200124_091122](https://user-images.githubusercontent.com/57667351/73054467-d0efb200-3e8a-11ea-8788-08ea3cc3582b.jpg)

**Comment by peppelg** [comment]
A me oggi sono arrivate due notifiche e l'icona c'è. 
Prima avevo avuto un problema con gradle e non aveva incluso nell'apk le icone.
Prova a scaricare (link: https://github.com/peppelg/argo_scuolanext_famiglia_unofficial_app/releases/latest/download/app-release.apk) e installare l'app un'altra volta

**Comment by bananabduh** [comment]
Okay aspetterò il prossimo voto e ti faccio sapere

**Comment by bananabduh** [comment]
Sì funziona perfettamente , bravo
